//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}eventTitle" minOccurs="0"/>
 *         &lt;element ref="{}date" minOccurs="0"/>
 *         &lt;element ref="{}place" minOccurs="0"/>
 *         &lt;element ref="{}eventDescription"/>
 *       &lt;/sequence>
 *       &lt;attribute name="tag" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="BornD"/>
 *             &lt;enumeration value="BornP"/>
 *             &lt;enumeration value="Born"/>
 *             &lt;enumeration value="ChrD"/>
 *             &lt;enumeration value="ChrP"/>
 *             &lt;enumeration value="Chr"/>
 *             &lt;enumeration value="DiedCause"/>
 *             &lt;enumeration value="DiedD"/>
 *             &lt;enumeration value="DiedP"/>
 *             &lt;enumeration value="Died"/>
 *             &lt;enumeration value="BapD"/>
 *             &lt;enumeration value="BapP"/>
 *             &lt;enumeration value="Bap"/>
 *             &lt;enumeration value="EndD"/>
 *             &lt;enumeration value="EndP"/>
 *             &lt;enumeration value="End"/>
 *             &lt;enumeration value="BurD"/>
 *             &lt;enumeration value="BurP"/>
 *             &lt;enumeration value="Bur"/>
 *             &lt;enumeration value="SToPD"/>
 *             &lt;enumeration value="SToPP"/>
 *             &lt;enumeration value="SToP"/>
 *             &lt;enumeration value="Title"/>
 *             &lt;enumeration value="Profession"/>
 *             &lt;enumeration value="Religion"/>
 *             &lt;enumeration value="LinkCToFather"/>
 *             &lt;enumeration value="LinkCToMother"/>
 *             &lt;enumeration value="LinkFToChildren"/>
 *             &lt;enumeration value="LinkMToChildren"/>
 *             &lt;enumeration value="Location"/>
 *             &lt;enumeration value="Emigration"/>
 *             &lt;enumeration value="Name"/>
 *             &lt;enumeration value="Headstone"/>
 *             &lt;enumeration value="WillAndTestament"/>
 *             &lt;enumeration value="AgeInYear"/>
 *             &lt;enumeration value="CemeteryName"/>
 *             &lt;enumeration value="CemeteryPlot"/>
 *             &lt;enumeration value="LinkPToDescendants"/>
 *             &lt;enumeration value="Home"/>
 *             &lt;enumeration value="OwnerOf"/>
 *             &lt;enumeration value="BapTemple"/>
 *             &lt;enumeration value="BapProxy"/>
 *             &lt;enumeration value="EndTemple"/>
 *             &lt;enumeration value="EndProxy"/>
 *             &lt;enumeration value="Personality"/>
 *             &lt;enumeration value="PersonComment"/>
 *             &lt;enumeration value="Hobbies"/>
 *             &lt;enumeration value="Education"/>
 *             &lt;enumeration value="Siblings"/>
 *             &lt;enumeration value="EditorNotes"/>
 *             &lt;enumeration value="TimeLine"/>
 *             &lt;enumeration value="BirthStats"/>
 *             &lt;enumeration value="Trivia"/>
 *             &lt;enumeration value="Uncategorized"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "eventTitle",
    "date",
    "place",
    "eventDescription"
})
@XmlRootElement(name = "event")
public class Event {

    protected EventTitle eventTitle;
    protected Date date;
    protected Place place;
    @XmlElement(required = true)
    protected EventDescription eventDescription;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String tag;

    /**
     * Gets the value of the eventTitle property.
     * 
     * @return
     *     possible object is
     *     {@link EventTitle }
     *     
     */
    public EventTitle getEventTitle() {
        return eventTitle;
    }

    /**
     * Sets the value of the eventTitle property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventTitle }
     *     
     */
    public void setEventTitle(EventTitle value) {
        this.eventTitle = value;
    }

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDate(Date value) {
        this.date = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link Place }
     *     
     */
    public Place getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place }
     *     
     */
    public void setPlace(Place value) {
        this.place = value;
    }

    /**
     * Gets the value of the eventDescription property.
     * 
     * @return
     *     possible object is
     *     {@link EventDescription }
     *     
     */
    public EventDescription getEventDescription() {
        return eventDescription;
    }

    /**
     * Sets the value of the eventDescription property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventDescription }
     *     
     */
    public void setEventDescription(EventDescription value) {
        this.eventDescription = value;
    }

    /**
     * Gets the value of the tag property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getTag() {
        return tag;
    }

    /**
     * Sets the value of the tag property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setTag(String value) {
        this.tag = value;
    }

}
