//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="surname" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="basePersonId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="baseMarriageId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="email" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="dataPath" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="outputPathTXT" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="outputPathHTML" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="outputPathWP" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsBaseUrlFile" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsBaseUrlWeb" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterFgs" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterPerInfo" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterPerIndex" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterPhoto" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterPhotoIndex" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterRef" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterRefIndex" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="formsCounterHome" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "family")
public class Family {

    @XmlValue
    protected String content;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String surname;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String basePersonId;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String baseMarriageId;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String email;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String dataPath;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String outputPathTXT;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String outputPathHTML;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String outputPathWP;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsBaseUrlFile;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsBaseUrlWeb;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterFgs;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterPerInfo;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterPerIndex;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterPhoto;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterPhotoIndex;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterRef;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterRefIndex;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String formsCounterHome;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the surname property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSurname() {
        return surname;
    }

    /**
     * Sets the value of the surname property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSurname(String value) {
        this.surname = value;
    }

    /**
     * Gets the value of the basePersonId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBasePersonId() {
        return basePersonId;
    }

    /**
     * Sets the value of the basePersonId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBasePersonId(String value) {
        this.basePersonId = value;
    }

    /**
     * Gets the value of the baseMarriageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getBaseMarriageId() {
        return baseMarriageId;
    }

    /**
     * Sets the value of the baseMarriageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setBaseMarriageId(String value) {
        this.baseMarriageId = value;
    }

    /**
     * Gets the value of the email property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEmail() {
        return email;
    }

    /**
     * Sets the value of the email property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEmail(String value) {
        this.email = value;
    }

    /**
     * Gets the value of the dataPath property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getDataPath() {
        return dataPath;
    }

    /**
     * Sets the value of the dataPath property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setDataPath(String value) {
        this.dataPath = value;
    }

    /**
     * Gets the value of the outputPathTXT property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputPathTXT() {
        return outputPathTXT;
    }

    /**
     * Sets the value of the outputPathTXT property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputPathTXT(String value) {
        this.outputPathTXT = value;
    }

    /**
     * Gets the value of the outputPathHTML property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputPathHTML() {
        return outputPathHTML;
    }

    /**
     * Sets the value of the outputPathHTML property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputPathHTML(String value) {
        this.outputPathHTML = value;
    }

    /**
     * Gets the value of the outputPathWP property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getOutputPathWP() {
        return outputPathWP;
    }

    /**
     * Sets the value of the outputPathWP property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setOutputPathWP(String value) {
        this.outputPathWP = value;
    }

    /**
     * Gets the value of the formsBaseUrlFile property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsBaseUrlFile() {
        return formsBaseUrlFile;
    }

    /**
     * Sets the value of the formsBaseUrlFile property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsBaseUrlFile(String value) {
        this.formsBaseUrlFile = value;
    }

    /**
     * Gets the value of the formsBaseUrlWeb property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsBaseUrlWeb() {
        return formsBaseUrlWeb;
    }

    /**
     * Sets the value of the formsBaseUrlWeb property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsBaseUrlWeb(String value) {
        this.formsBaseUrlWeb = value;
    }

    /**
     * Gets the value of the formsCounterFgs property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterFgs() {
        return formsCounterFgs;
    }

    /**
     * Sets the value of the formsCounterFgs property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterFgs(String value) {
        this.formsCounterFgs = value;
    }

    /**
     * Gets the value of the formsCounterPerInfo property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterPerInfo() {
        return formsCounterPerInfo;
    }

    /**
     * Sets the value of the formsCounterPerInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterPerInfo(String value) {
        this.formsCounterPerInfo = value;
    }

    /**
     * Gets the value of the formsCounterPerIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterPerIndex() {
        return formsCounterPerIndex;
    }

    /**
     * Sets the value of the formsCounterPerIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterPerIndex(String value) {
        this.formsCounterPerIndex = value;
    }

    /**
     * Gets the value of the formsCounterPhoto property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterPhoto() {
        return formsCounterPhoto;
    }

    /**
     * Sets the value of the formsCounterPhoto property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterPhoto(String value) {
        this.formsCounterPhoto = value;
    }

    /**
     * Gets the value of the formsCounterPhotoIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterPhotoIndex() {
        return formsCounterPhotoIndex;
    }

    /**
     * Sets the value of the formsCounterPhotoIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterPhotoIndex(String value) {
        this.formsCounterPhotoIndex = value;
    }

    /**
     * Gets the value of the formsCounterRef property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterRef() {
        return formsCounterRef;
    }

    /**
     * Sets the value of the formsCounterRef property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterRef(String value) {
        this.formsCounterRef = value;
    }

    /**
     * Gets the value of the formsCounterRefIndex property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterRefIndex() {
        return formsCounterRefIndex;
    }

    /**
     * Sets the value of the formsCounterRefIndex property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterRefIndex(String value) {
        this.formsCounterRefIndex = value;
    }

    /**
     * Gets the value of the formsCounterHome property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getFormsCounterHome() {
        return formsCounterHome;
    }

    /**
     * Sets the value of the formsCounterHome property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setFormsCounterHome(String value) {
        this.formsCounterHome = value;
    }

}
