//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}baptismInfo" minOccurs="0"/>
 *         &lt;element ref="{}endowmentInfo" minOccurs="0"/>
 *         &lt;element ref="{}sealToParentsInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "baptismInfo",
    "endowmentInfo",
    "sealToParentsInfo"
})
@XmlRootElement(name = "ldsInfo")
public class LdsInfo {

    protected BaptismInfo baptismInfo;
    protected EndowmentInfo endowmentInfo;
    protected SealToParentsInfo sealToParentsInfo;

    /**
     * Gets the value of the baptismInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BaptismInfo }
     *     
     */
    public BaptismInfo getBaptismInfo() {
        return baptismInfo;
    }

    /**
     * Sets the value of the baptismInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BaptismInfo }
     *     
     */
    public void setBaptismInfo(BaptismInfo value) {
        this.baptismInfo = value;
    }

    /**
     * Gets the value of the endowmentInfo property.
     * 
     * @return
     *     possible object is
     *     {@link EndowmentInfo }
     *     
     */
    public EndowmentInfo getEndowmentInfo() {
        return endowmentInfo;
    }

    /**
     * Sets the value of the endowmentInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link EndowmentInfo }
     *     
     */
    public void setEndowmentInfo(EndowmentInfo value) {
        this.endowmentInfo = value;
    }

    /**
     * Gets the value of the sealToParentsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SealToParentsInfo }
     *     
     */
    public SealToParentsInfo getSealToParentsInfo() {
        return sealToParentsInfo;
    }

    /**
     * Sets the value of the sealToParentsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SealToParentsInfo }
     *     
     */
    public void setSealToParentsInfo(SealToParentsInfo value) {
        this.sealToParentsInfo = value;
    }

}
