//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}info" minOccurs="0"/>
 *         &lt;element ref="{}sealToSpouseInfo" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "info",
    "sealToSpouseInfo"
})
@XmlRootElement(name = "marriageInfo")
public class MarriageInfo {

    protected Info info;
    protected SealToSpouseInfo sealToSpouseInfo;

    /**
     * Gets the value of the info property.
     * 
     * @return
     *     possible object is
     *     {@link Info }
     *     
     */
    public Info getInfo() {
        return info;
    }

    /**
     * Sets the value of the info property.
     * 
     * @param value
     *     allowed object is
     *     {@link Info }
     *     
     */
    public void setInfo(Info value) {
        this.info = value;
    }

    /**
     * Gets the value of the sealToSpouseInfo property.
     * 
     * @return
     *     possible object is
     *     {@link SealToSpouseInfo }
     *     
     */
    public SealToSpouseInfo getSealToSpouseInfo() {
        return sealToSpouseInfo;
    }

    /**
     * Sets the value of the sealToSpouseInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link SealToSpouseInfo }
     *     
     */
    public void setSealToSpouseInfo(SealToSpouseInfo value) {
        this.sealToSpouseInfo = value;
    }

}
