//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlElementDecl;
import javax.xml.bind.annotation.XmlRegistry;
import javax.xml.namespace.QName;


/**
 * This object contains factory methods for each 
 * Java content interface and Java element interface 
 * generated in the home.genealogy.schema.all package. 
 * <p>An ObjectFactory allows you to programatically 
 * construct new instances of the Java representation 
 * for XML content. The Java representation of XML 
 * content can consist of schema derived interfaces 
 * and classes representing the binding of schema 
 * type definitions, element declarations and model 
 * groups.  Factory methods for each of these are 
 * provided in this class.
 * 
 */
@XmlRegistry
public class ObjectFactory {

    private final static QName _VolumeNumbers_QNAME = new QName("", "volumeNumbers");
    private final static QName _StudioName_QNAME = new QName("", "studioName");
    private final static QName _PageNumbers_QNAME = new QName("", "pageNumbers");
    private final static QName _FormText_QNAME = new QName("", "formText");
    private final static QName _EntryNumbers_QNAME = new QName("", "entryNumbers");
    private final static QName _EditorComment_QNAME = new QName("", "editorComment");
    private final static QName _AltSpelling_QNAME = new QName("", "altSpelling");
    private final static QName _ChapterNumbers_QNAME = new QName("", "chapterNumbers");
    private final static QName _PrivateText_QNAME = new QName("", "privateText");
    private final static QName _Moniker_QNAME = new QName("", "moniker");

    /**
     * Create a new ObjectFactory that can be used to create new instances of schema derived classes for package: home.genealogy.schema.all
     * 
     */
    public ObjectFactory() {
    }

    /**
     * Create an instance of {@link MiddleName }
     * 
     */
    public MiddleName createMiddleName() {
        return new MiddleName();
    }

    /**
     * Create an instance of {@link EventGroup }
     * 
     */
    public EventGroup createEventGroup() {
        return new EventGroup();
    }

    /**
     * Create an instance of {@link Place1Level }
     * 
     */
    public Place1Level createPlace1Level() {
        return new Place1Level();
    }

    /**
     * Create an instance of {@link Photos }
     * 
     */
    public Photos createPhotos() {
        return new Photos();
    }

    /**
     * Create an instance of {@link Institution }
     * 
     */
    public Institution createInstitution() {
        return new Institution();
    }

    /**
     * Create an instance of {@link EventDescription }
     * 
     */
    public EventDescription createEventDescription() {
        return new EventDescription();
    }

    /**
     * Create an instance of {@link EventTitle }
     * 
     */
    public EventTitle createEventTitle() {
        return new EventTitle();
    }

    /**
     * Create an instance of {@link DateRange }
     * 
     */
    public DateRange createDateRange() {
        return new DateRange();
    }

    /**
     * Create an instance of {@link ReferenceEntryId }
     * 
     */
    public ReferenceEntryId createReferenceEntryId() {
        return new ReferenceEntryId();
    }

    /**
     * Create an instance of {@link Reference }
     * 
     */
    public Reference createReference() {
        return new Reference();
    }

    /**
     * Create an instance of {@link SealToSpouseInfo }
     * 
     */
    public SealToSpouseInfo createSealToSpouseInfo() {
        return new SealToSpouseInfo();
    }

    /**
     * Create an instance of {@link Persons }
     * 
     */
    public Persons createPersons() {
        return new Persons();
    }

    /**
     * Create an instance of {@link Citation }
     * 
     */
    public Citation createCitation() {
        return new Citation();
    }

    /**
     * Create an instance of {@link Marriages }
     * 
     */
    public Marriages createMarriages() {
        return new Marriages();
    }

    /**
     * Create an instance of {@link Table }
     * 
     */
    public Table createTable() {
        return new Table();
    }

    /**
     * Create an instance of {@link AsOf }
     * 
     */
    public AsOf createAsOf() {
        return new AsOf();
    }

    /**
     * Create an instance of {@link Profession }
     * 
     */
    public Profession createProfession() {
        return new Profession();
    }

    /**
     * Create an instance of {@link Religion }
     * 
     */
    public Religion createReligion() {
        return new Religion();
    }

    /**
     * Create an instance of {@link Info }
     * 
     */
    public Info createInfo() {
        return new Info();
    }

    /**
     * Create an instance of {@link CallNumber }
     * 
     */
    public CallNumber createCallNumber() {
        return new CallNumber();
    }

    /**
     * Create an instance of {@link File }
     * 
     */
    public File createFile() {
        return new File();
    }

    /**
     * Create an instance of {@link Location }
     * 
     */
    public Location createLocation() {
        return new Location();
    }

    /**
     * Create an instance of {@link Place3Level }
     * 
     */
    public Place3Level createPlace3Level() {
        return new Place3Level();
    }

    /**
     * Create an instance of {@link GlobalCoordinates }
     * 
     */
    public GlobalCoordinates createGlobalCoordinates() {
        return new GlobalCoordinates();
    }

    /**
     * Create an instance of {@link PersonName }
     * 
     */
    public PersonName createPersonName() {
        return new PersonName();
    }

    /**
     * Create an instance of {@link MarriageTagType }
     * 
     */
    public MarriageTagType createMarriageTagType() {
        return new MarriageTagType();
    }

    /**
     * Create an instance of {@link LdsInfo }
     * 
     */
    public LdsInfo createLdsInfo() {
        return new LdsInfo();
    }

    /**
     * Create an instance of {@link LastName }
     * 
     */
    public LastName createLastName() {
        return new LastName();
    }

    /**
     * Create an instance of {@link BaptismInfo }
     * 
     */
    public BaptismInfo createBaptismInfo() {
        return new BaptismInfo();
    }

    /**
     * Create an instance of {@link ReferenceId }
     * 
     */
    public ReferenceId createReferenceId() {
        return new ReferenceId();
    }

    /**
     * Create an instance of {@link Place }
     * 
     */
    public Place createPlace() {
        return new Place();
    }

    /**
     * Create an instance of {@link Authority }
     * 
     */
    public Authority createAuthority() {
        return new Authority();
    }

    /**
     * Create an instance of {@link PhotoId }
     * 
     */
    public PhotoId createPhotoId() {
        return new PhotoId();
    }

    /**
     * Create an instance of {@link Photo }
     * 
     */
    public Photo createPhoto() {
        return new Photo();
    }

    /**
     * Create an instance of {@link Longitude }
     * 
     */
    public Longitude createLongitude() {
        return new Longitude();
    }

    /**
     * Create an instance of {@link Family }
     * 
     */
    public Family createFamily() {
        return new Family();
    }

    /**
     * Create an instance of {@link Place2Level }
     * 
     */
    public Place2Level createPlace2Level() {
        return new Place2Level();
    }

    /**
     * Create an instance of {@link Latitude }
     * 
     */
    public Latitude createLatitude() {
        return new Latitude();
    }

    /**
     * Create an instance of {@link Source }
     * 
     */
    public Source createSource() {
        return new Source();
    }

    /**
     * Create an instance of {@link Caption }
     * 
     */
    public Caption createCaption() {
        return new Caption();
    }

    /**
     * Create an instance of {@link Author }
     * 
     */
    public Author createAuthor() {
        return new Author();
    }

    /**
     * Create an instance of {@link Description }
     * 
     */
    public Description createDescription() {
        return new Description();
    }

    /**
     * Create an instance of {@link FirstName }
     * 
     */
    public FirstName createFirstName() {
        return new FirstName();
    }

    /**
     * Create an instance of {@link TagGroup }
     * 
     */
    public TagGroup createTagGroup() {
        return new TagGroup();
    }

    /**
     * Create an instance of {@link Classification }
     * 
     */
    public Classification createClassification() {
        return new Classification();
    }

    /**
     * Create an instance of {@link Publisher }
     * 
     */
    public Publisher createPublisher() {
        return new Publisher();
    }

    /**
     * Create an instance of {@link Body }
     * 
     */
    public Body createBody() {
        return new Body();
    }

    /**
     * Create an instance of {@link Paragraph }
     * 
     */
    public Paragraph createParagraph() {
        return new Paragraph();
    }

    /**
     * Create an instance of {@link Termination }
     * 
     */
    public Termination createTermination() {
        return new Termination();
    }

    /**
     * Create an instance of {@link MarriageId }
     * 
     */
    public MarriageId createMarriageId() {
        return new MarriageId();
    }

    /**
     * Create an instance of {@link Company }
     * 
     */
    public Company createCompany() {
        return new Company();
    }

    /**
     * Create an instance of {@link Row }
     * 
     */
    public Row createRow() {
        return new Row();
    }

    /**
     * Create an instance of {@link Comment }
     * 
     */
    public Comment createComment() {
        return new Comment();
    }

    /**
     * Create an instance of {@link Address }
     * 
     */
    public Address createAddress() {
        return new Address();
    }

    /**
     * Create an instance of {@link Column }
     * 
     */
    public Column createColumn() {
        return new Column();
    }

    /**
     * Create an instance of {@link Commentary }
     * 
     */
    public Commentary createCommentary() {
        return new Commentary();
    }

    /**
     * Create an instance of {@link PersonTag }
     * 
     */
    public PersonTag createPersonTag() {
        return new PersonTag();
    }

    /**
     * Create an instance of {@link Title }
     * 
     */
    public Title createTitle() {
        return new Title();
    }

    /**
     * Create an instance of {@link Marriage }
     * 
     */
    public Marriage createMarriage() {
        return new Marriage();
    }

    /**
     * Create an instance of {@link EntryTitle }
     * 
     */
    public EntryTitle createEntryTitle() {
        return new EntryTitle();
    }

    /**
     * Create an instance of {@link GroupName }
     * 
     */
    public GroupName createGroupName() {
        return new GroupName();
    }

    /**
     * Create an instance of {@link Entry }
     * 
     */
    public Entry createEntry() {
        return new Entry();
    }

    /**
     * Create an instance of {@link Place4Level }
     * 
     */
    public Place4Level createPlace4Level() {
        return new Place4Level();
    }

    /**
     * Create an instance of {@link DeathInfo }
     * 
     */
    public DeathInfo createDeathInfo() {
        return new DeathInfo();
    }

    /**
     * Create an instance of {@link SealToParentsInfo }
     * 
     */
    public SealToParentsInfo createSealToParentsInfo() {
        return new SealToParentsInfo();
    }

    /**
     * Create an instance of {@link FileList }
     * 
     */
    public FileList createFileList() {
        return new FileList();
    }

    /**
     * Create an instance of {@link NickName }
     * 
     */
    public NickName createNickName() {
        return new NickName();
    }

    /**
     * Create an instance of {@link References }
     * 
     */
    public References createReferences() {
        return new References();
    }

    /**
     * Create an instance of {@link Owner }
     * 
     */
    public Owner createOwner() {
        return new Owner();
    }

    /**
     * Create an instance of {@link BirthInfo }
     * 
     */
    public BirthInfo createBirthInfo() {
        return new BirthInfo();
    }

    /**
     * Create an instance of {@link Event }
     * 
     */
    public Event createEvent() {
        return new Event();
    }

    /**
     * Create an instance of {@link Photographer }
     * 
     */
    public Photographer createPhotographer() {
        return new Photographer();
    }

    /**
     * Create an instance of {@link BurialInfo }
     * 
     */
    public BurialInfo createBurialInfo() {
        return new BurialInfo();
    }

    /**
     * Create an instance of {@link ChrInfo }
     * 
     */
    public ChrInfo createChrInfo() {
        return new ChrInfo();
    }

    /**
     * Create an instance of {@link MarriageInfo }
     * 
     */
    public MarriageInfo createMarriageInfo() {
        return new MarriageInfo();
    }

    /**
     * Create an instance of {@link MarriageTag }
     * 
     */
    public MarriageTag createMarriageTag() {
        return new MarriageTag();
    }

    /**
     * Create an instance of {@link EndowmentInfo }
     * 
     */
    public EndowmentInfo createEndowmentInfo() {
        return new EndowmentInfo();
    }

    /**
     * Create an instance of {@link PersonIdentification }
     * 
     */
    public PersonIdentification createPersonIdentification() {
        return new PersonIdentification();
    }

    /**
     * Create an instance of {@link Person }
     * 
     */
    public Person createPerson() {
        return new Person();
    }

    /**
     * Create an instance of {@link Proxy }
     * 
     */
    public Proxy createProxy() {
        return new Proxy();
    }

    /**
     * Create an instance of {@link SeeAlso }
     * 
     */
    public SeeAlso createSeeAlso() {
        return new SeeAlso();
    }

    /**
     * Create an instance of {@link WGS84 }
     * 
     */
    public WGS84 createWGS84() {
        return new WGS84();
    }

    /**
     * Create an instance of {@link Date }
     * 
     */
    public Date createDate() {
        return new Date();
    }

    /**
     * Create an instance of {@link Space }
     * 
     */
    public Space createSpace() {
        return new Space();
    }

    /**
     * Create an instance of {@link Header }
     * 
     */
    public Header createHeader() {
        return new Header();
    }

    /**
     * Create an instance of {@link Tag }
     * 
     */
    public Tag createTag() {
        return new Tag();
    }

    /**
     * Create an instance of {@link PersonTagType }
     * 
     */
    public PersonTagType createPersonTagType() {
        return new PersonTagType();
    }

    /**
     * Create an instance of {@link PersonId }
     * 
     */
    public PersonId createPersonId() {
        return new PersonId();
    }

    /**
     * Create an instance of {@link PublishedIn }
     * 
     */
    public PublishedIn createPublishedIn() {
        return new PublishedIn();
    }

    /**
     * Create an instance of {@link Singleton }
     * 
     */
    public Singleton createSingleton() {
        return new Singleton();
    }

    /**
     * Create an instance of {@link DateOr }
     * 
     */
    public DateOr createDateOr() {
        return new DateOr();
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "volumeNumbers")
    public JAXBElement<String> createVolumeNumbers(String value) {
        return new JAXBElement<String>(_VolumeNumbers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "studioName")
    public JAXBElement<String> createStudioName(String value) {
        return new JAXBElement<String>(_StudioName_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "pageNumbers")
    public JAXBElement<String> createPageNumbers(String value) {
        return new JAXBElement<String>(_PageNumbers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "formText")
    public JAXBElement<String> createFormText(String value) {
        return new JAXBElement<String>(_FormText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "entryNumbers")
    public JAXBElement<String> createEntryNumbers(String value) {
        return new JAXBElement<String>(_EntryNumbers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "editorComment")
    public JAXBElement<String> createEditorComment(String value) {
        return new JAXBElement<String>(_EditorComment_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "altSpelling")
    public JAXBElement<String> createAltSpelling(String value) {
        return new JAXBElement<String>(_AltSpelling_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "chapterNumbers")
    public JAXBElement<String> createChapterNumbers(String value) {
        return new JAXBElement<String>(_ChapterNumbers_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "privateText")
    public JAXBElement<String> createPrivateText(String value) {
        return new JAXBElement<String>(_PrivateText_QNAME, String.class, null, value);
    }

    /**
     * Create an instance of {@link JAXBElement }{@code <}{@link String }{@code >}}
     * 
     */
    @XmlElementDecl(namespace = "", name = "moniker")
    public JAXBElement<String> createMoniker(String value) {
        return new JAXBElement<String>(_Moniker_QNAME, String.class, null, value);
    }

}
