//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.JAXBElement;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElementRef;
import javax.xml.bind.annotation.XmlElementRefs;
import javax.xml.bind.annotation.XmlMixed;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;choice maxOccurs="unbounded" minOccurs="0">
 *         &lt;element ref="{}privateText"/>
 *         &lt;element ref="{}formText"/>
 *         &lt;element ref="{}editorComment"/>
 *         &lt;element ref="{}space"/>
 *         &lt;element ref="{}personId"/>
 *         &lt;element ref="{}marriageId"/>
 *         &lt;element ref="{}referenceId"/>
 *         &lt;element ref="{}referenceEntryId"/>
 *         &lt;element ref="{}photoId"/>
 *         &lt;element ref="{}tag"/>
 *       &lt;/choice>
 *       &lt;attribute name="indent" default="Yes">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="No"/>
 *             &lt;enumeration value="Yes"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="lineEnd" default="HdRet">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="HdRet"/>
 *             &lt;enumeration value="None"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "paragraph")
public class Paragraph {

    @XmlElementRefs({
        @XmlElementRef(name = "photoId", type = PhotoId.class),
        @XmlElementRef(name = "space", type = Space.class),
        @XmlElementRef(name = "marriageId", type = MarriageId.class),
        @XmlElementRef(name = "tag", type = Tag.class),
        @XmlElementRef(name = "personId", type = PersonId.class),
        @XmlElementRef(name = "referenceEntryId", type = ReferenceEntryId.class),
        @XmlElementRef(name = "formText", type = JAXBElement.class),
        @XmlElementRef(name = "referenceId", type = ReferenceId.class),
        @XmlElementRef(name = "privateText", type = JAXBElement.class),
        @XmlElementRef(name = "editorComment", type = JAXBElement.class)
    })
    @XmlMixed
    protected List<Object> content;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String indent;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String lineEnd;

    /**
     * Gets the value of the content property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the content property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getContent().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link PhotoId }
     * {@link String }
     * {@link MarriageId }
     * {@link Space }
     * {@link Tag }
     * {@link PersonId }
     * {@link ReferenceId }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link ReferenceEntryId }
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * {@link JAXBElement }{@code <}{@link String }{@code >}
     * 
     * 
     */
    public List<Object> getContent() {
        if (content == null) {
            content = new ArrayList<Object>();
        }
        return this.content;
    }

    /**
     * Gets the value of the indent property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getIndent() {
        if (indent == null) {
            return "Yes";
        } else {
            return indent;
        }
    }

    /**
     * Sets the value of the indent property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setIndent(String value) {
        this.indent = value;
    }

    /**
     * Gets the value of the lineEnd property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLineEnd() {
        if (lineEnd == null) {
            return "HdRet";
        } else {
            return lineEnd;
        }
    }

    /**
     * Sets the value of the lineEnd property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLineEnd(String value) {
        this.lineEnd = value;
    }

}
