//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.XmlValue;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;attribute name="type" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="BornD"/>
 *             &lt;enumeration value="BornP"/>
 *             &lt;enumeration value="ChrD"/>
 *             &lt;enumeration value="ChrP"/>
 *             &lt;enumeration value="DiedCause"/>
 *             &lt;enumeration value="DiedD"/>
 *             &lt;enumeration value="DiedP"/>
 *             &lt;enumeration value="BapD"/>
 *             &lt;enumeration value="BapP"/>
 *             &lt;enumeration value="EndD"/>
 *             &lt;enumeration value="EndP"/>
 *             &lt;enumeration value="BurD"/>
 *             &lt;enumeration value="BurP"/>
 *             &lt;enumeration value="SToPD"/>
 *             &lt;enumeration value="SToPP"/>
 *             &lt;enumeration value="Title"/>
 *             &lt;enumeration value="Profession"/>
 *             &lt;enumeration value="Religion"/>
 *             &lt;enumeration value="LinkCToFather"/>
 *             &lt;enumeration value="LinkCToMother"/>
 *             &lt;enumeration value="LinkFToChildren"/>
 *             &lt;enumeration value="LinkMToChildren"/>
 *             &lt;enumeration value="Location"/>
 *             &lt;enumeration value="Emigration"/>
 *             &lt;enumeration value="Name"/>
 *             &lt;enumeration value="Headstone"/>
 *             &lt;enumeration value="WillAndTestament"/>
 *             &lt;enumeration value="AgeInYear"/>
 *             &lt;enumeration value="CemeteryName"/>
 *             &lt;enumeration value="Trivia"/>
 *             &lt;enumeration value="CemeteryPlot"/>
 *             &lt;enumeration value="LinkPToDescendants"/>
 *             &lt;enumeration value="Portrait"/>
 *             &lt;enumeration value="Home"/>
 *             &lt;enumeration value="PictureOf"/>
 *             &lt;enumeration value="OwnerOf"/>
 *             &lt;enumeration value="BapTemple"/>
 *             &lt;enumeration value="BapProxy"/>
 *             &lt;enumeration value="EndTemple"/>
 *             &lt;enumeration value="EndProxy"/>
 *             &lt;enumeration value="ExtFamilyPicture"/>
 *             &lt;enumeration value="ThreeGeneration"/>
 *             &lt;enumeration value="FourGeneration"/>
 *             &lt;enumeration value="FiveGeneration"/>
 *             &lt;enumeration value="Obituary"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="quality" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="HIGH"/>
 *             &lt;enumeration value="MEDIUM"/>
 *             &lt;enumeration value="LOW"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "content"
})
@XmlRootElement(name = "personTagType")
public class PersonTagType {

    @XmlValue
    protected String content;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String type;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String quality;

    /**
     * Gets the value of the content property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getContent() {
        return content;
    }

    /**
     * Sets the value of the content property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setContent(String value) {
        this.content = value;
    }

    /**
     * Gets the value of the type property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getType() {
        return type;
    }

    /**
     * Sets the value of the type property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setType(String value) {
        this.type = value;
    }

    /**
     * Gets the value of the quality property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getQuality() {
        return quality;
    }

    /**
     * Sets the value of the quality property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setQuality(String value) {
        this.quality = value;
    }

}
