//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}date" minOccurs="0"/>
 *         &lt;element ref="{}place" minOccurs="0"/>
 *         &lt;element ref="{}caption" minOccurs="0"/>
 *         &lt;element ref="{}photographer" minOccurs="0"/>
 *         &lt;element ref="{}owner" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}commentary" minOccurs="0"/>
 *         &lt;element ref="{}tagGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="mediaType">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="DigitalPhoto"/>
 *             &lt;enumeration value="Painting"/>
 *             &lt;enumeration value="Photo"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "date",
    "place",
    "caption",
    "photographer",
    "owner",
    "commentary",
    "tagGroup"
})
@XmlRootElement(name = "singleton")
public class Singleton {

    protected Date date;
    protected Place place;
    protected Caption caption;
    protected Photographer photographer;
    protected List<Owner> owner;
    protected Commentary commentary;
    protected TagGroup tagGroup;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String mediaType;

    /**
     * Gets the value of the date property.
     * 
     * @return
     *     possible object is
     *     {@link Date }
     *     
     */
    public Date getDate() {
        return date;
    }

    /**
     * Sets the value of the date property.
     * 
     * @param value
     *     allowed object is
     *     {@link Date }
     *     
     */
    public void setDate(Date value) {
        this.date = value;
    }

    /**
     * Gets the value of the place property.
     * 
     * @return
     *     possible object is
     *     {@link Place }
     *     
     */
    public Place getPlace() {
        return place;
    }

    /**
     * Sets the value of the place property.
     * 
     * @param value
     *     allowed object is
     *     {@link Place }
     *     
     */
    public void setPlace(Place value) {
        this.place = value;
    }

    /**
     * Gets the value of the caption property.
     * 
     * @return
     *     possible object is
     *     {@link Caption }
     *     
     */
    public Caption getCaption() {
        return caption;
    }

    /**
     * Sets the value of the caption property.
     * 
     * @param value
     *     allowed object is
     *     {@link Caption }
     *     
     */
    public void setCaption(Caption value) {
        this.caption = value;
    }

    /**
     * Gets the value of the photographer property.
     * 
     * @return
     *     possible object is
     *     {@link Photographer }
     *     
     */
    public Photographer getPhotographer() {
        return photographer;
    }

    /**
     * Sets the value of the photographer property.
     * 
     * @param value
     *     allowed object is
     *     {@link Photographer }
     *     
     */
    public void setPhotographer(Photographer value) {
        this.photographer = value;
    }

    /**
     * Gets the value of the owner property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the owner property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getOwner().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Owner }
     * 
     * 
     */
    public List<Owner> getOwner() {
        if (owner == null) {
            owner = new ArrayList<Owner>();
        }
        return this.owner;
    }

    /**
     * Gets the value of the commentary property.
     * 
     * @return
     *     possible object is
     *     {@link Commentary }
     *     
     */
    public Commentary getCommentary() {
        return commentary;
    }

    /**
     * Sets the value of the commentary property.
     * 
     * @param value
     *     allowed object is
     *     {@link Commentary }
     *     
     */
    public void setCommentary(Commentary value) {
        this.commentary = value;
    }

    /**
     * Gets the value of the tagGroup property.
     * 
     * @return
     *     possible object is
     *     {@link TagGroup }
     *     
     */
    public TagGroup getTagGroup() {
        return tagGroup;
    }

    /**
     * Sets the value of the tagGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link TagGroup }
     *     
     */
    public void setTagGroup(TagGroup value) {
        this.tagGroup = value;
    }

    /**
     * Gets the value of the mediaType property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMediaType() {
        return mediaType;
    }

    /**
     * Sets the value of the mediaType property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMediaType(String value) {
        this.mediaType = value;
    }

}
