//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}volumeNumbers" minOccurs="0"/>
 *         &lt;element ref="{}chapterNumbers" minOccurs="0"/>
 *         &lt;element ref="{}pageNumbers" minOccurs="0"/>
 *         &lt;element ref="{}entryNumbers" minOccurs="0"/>
 *         &lt;element ref="{}paragraph" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "volumeNumbers",
    "chapterNumbers",
    "pageNumbers",
    "entryNumbers",
    "paragraph"
})
@XmlRootElement(name = "header")
public class Header {

    protected String volumeNumbers;
    protected String chapterNumbers;
    protected String pageNumbers;
    protected String entryNumbers;
    protected List<Paragraph> paragraph;

    /**
     * Gets the value of the volumeNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVolumeNumbers() {
        return volumeNumbers;
    }

    /**
     * Sets the value of the volumeNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVolumeNumbers(String value) {
        this.volumeNumbers = value;
    }

    /**
     * Gets the value of the chapterNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getChapterNumbers() {
        return chapterNumbers;
    }

    /**
     * Sets the value of the chapterNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setChapterNumbers(String value) {
        this.chapterNumbers = value;
    }

    /**
     * Gets the value of the pageNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPageNumbers() {
        return pageNumbers;
    }

    /**
     * Sets the value of the pageNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPageNumbers(String value) {
        this.pageNumbers = value;
    }

    /**
     * Gets the value of the entryNumbers property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getEntryNumbers() {
        return entryNumbers;
    }

    /**
     * Sets the value of the entryNumbers property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setEntryNumbers(String value) {
        this.entryNumbers = value;
    }

    /**
     * Gets the value of the paragraph property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the paragraph property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getParagraph().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Paragraph }
     * 
     * 
     */
    public List<Paragraph> getParagraph() {
        if (paragraph == null) {
            paragraph = new ArrayList<Paragraph>();
        }
        return this.paragraph;
    }

}
