//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}marriageTagType" maxOccurs="unbounded"/>
 *       &lt;/sequence>
 *       &lt;attribute name="marriageId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "marriageTagType"
})
@XmlRootElement(name = "marriageTag")
public class MarriageTag {

    @XmlElement(required = true)
    protected List<MarriageTagType> marriageTagType;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String marriageId;

    /**
     * Gets the value of the marriageTagType property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the marriageTagType property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMarriageTagType().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link MarriageTagType }
     * 
     * 
     */
    public List<MarriageTagType> getMarriageTagType() {
        if (marriageTagType == null) {
            marriageTagType = new ArrayList<MarriageTagType>();
        }
        return this.marriageTagType;
    }

    /**
     * Gets the value of the marriageId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getMarriageId() {
        return marriageId;
    }

    /**
     * Sets the value of the marriageId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setMarriageId(String value) {
        this.marriageId = value;
    }

}
