//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;
import javax.xml.bind.annotation.adapters.CollapsedStringAdapter;
import javax.xml.bind.annotation.adapters.XmlJavaTypeAdapter;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}personIdentification"/>
 *         &lt;element ref="{}profession" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}religion" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}birthInfo" minOccurs="0"/>
 *         &lt;element ref="{}chrInfo" minOccurs="0"/>
 *         &lt;element ref="{}deathInfo" minOccurs="0"/>
 *         &lt;element ref="{}burialInfo" minOccurs="0"/>
 *         &lt;element ref="{}ldsInfo" minOccurs="0"/>
 *         &lt;element ref="{}eventGroup" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="version" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="personId" use="required" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="parentId" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="relationshipToPrimary" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="adopted">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Yes"/>
 *             &lt;enumeration value="No"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="afn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="ssn" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *       &lt;attribute name="gender" use="required">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="MALE"/>
 *             &lt;enumeration value="FEMALE"/>
 *             &lt;enumeration value="UNKNOWN"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *       &lt;attribute name="living">
 *         &lt;simpleType>
 *           &lt;restriction base="{http://www.w3.org/2001/XMLSchema}token">
 *             &lt;enumeration value="Yes"/>
 *             &lt;enumeration value="No"/>
 *           &lt;/restriction>
 *         &lt;/simpleType>
 *       &lt;/attribute>
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personIdentification",
    "profession",
    "religion",
    "birthInfo",
    "chrInfo",
    "deathInfo",
    "burialInfo",
    "ldsInfo",
    "eventGroup"
})
@XmlRootElement(name = "person")
public class Person {

    @XmlElement(required = true)
    protected PersonIdentification personIdentification;
    protected List<Profession> profession;
    protected List<Religion> religion;
    protected BirthInfo birthInfo;
    protected ChrInfo chrInfo;
    protected DeathInfo deathInfo;
    protected BurialInfo burialInfo;
    protected LdsInfo ldsInfo;
    protected EventGroup eventGroup;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String version;
    @XmlAttribute(required = true)
    @XmlSchemaType(name = "anySimpleType")
    protected String personId;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String parentId;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String relationshipToPrimary;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String adopted;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String afn;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String ssn;
    @XmlAttribute(required = true)
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String gender;
    @XmlAttribute
    @XmlJavaTypeAdapter(CollapsedStringAdapter.class)
    protected String living;

    /**
     * Gets the value of the personIdentification property.
     * 
     * @return
     *     possible object is
     *     {@link PersonIdentification }
     *     
     */
    public PersonIdentification getPersonIdentification() {
        return personIdentification;
    }

    /**
     * Sets the value of the personIdentification property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonIdentification }
     *     
     */
    public void setPersonIdentification(PersonIdentification value) {
        this.personIdentification = value;
    }

    /**
     * Gets the value of the profession property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the profession property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getProfession().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Profession }
     * 
     * 
     */
    public List<Profession> getProfession() {
        if (profession == null) {
            profession = new ArrayList<Profession>();
        }
        return this.profession;
    }

    /**
     * Gets the value of the religion property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the religion property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getReligion().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link Religion }
     * 
     * 
     */
    public List<Religion> getReligion() {
        if (religion == null) {
            religion = new ArrayList<Religion>();
        }
        return this.religion;
    }

    /**
     * Gets the value of the birthInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BirthInfo }
     *     
     */
    public BirthInfo getBirthInfo() {
        return birthInfo;
    }

    /**
     * Sets the value of the birthInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BirthInfo }
     *     
     */
    public void setBirthInfo(BirthInfo value) {
        this.birthInfo = value;
    }

    /**
     * Gets the value of the chrInfo property.
     * 
     * @return
     *     possible object is
     *     {@link ChrInfo }
     *     
     */
    public ChrInfo getChrInfo() {
        return chrInfo;
    }

    /**
     * Sets the value of the chrInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link ChrInfo }
     *     
     */
    public void setChrInfo(ChrInfo value) {
        this.chrInfo = value;
    }

    /**
     * Gets the value of the deathInfo property.
     * 
     * @return
     *     possible object is
     *     {@link DeathInfo }
     *     
     */
    public DeathInfo getDeathInfo() {
        return deathInfo;
    }

    /**
     * Sets the value of the deathInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link DeathInfo }
     *     
     */
    public void setDeathInfo(DeathInfo value) {
        this.deathInfo = value;
    }

    /**
     * Gets the value of the burialInfo property.
     * 
     * @return
     *     possible object is
     *     {@link BurialInfo }
     *     
     */
    public BurialInfo getBurialInfo() {
        return burialInfo;
    }

    /**
     * Sets the value of the burialInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link BurialInfo }
     *     
     */
    public void setBurialInfo(BurialInfo value) {
        this.burialInfo = value;
    }

    /**
     * Gets the value of the ldsInfo property.
     * 
     * @return
     *     possible object is
     *     {@link LdsInfo }
     *     
     */
    public LdsInfo getLdsInfo() {
        return ldsInfo;
    }

    /**
     * Sets the value of the ldsInfo property.
     * 
     * @param value
     *     allowed object is
     *     {@link LdsInfo }
     *     
     */
    public void setLdsInfo(LdsInfo value) {
        this.ldsInfo = value;
    }

    /**
     * Gets the value of the eventGroup property.
     * 
     * @return
     *     possible object is
     *     {@link EventGroup }
     *     
     */
    public EventGroup getEventGroup() {
        return eventGroup;
    }

    /**
     * Sets the value of the eventGroup property.
     * 
     * @param value
     *     allowed object is
     *     {@link EventGroup }
     *     
     */
    public void setEventGroup(EventGroup value) {
        this.eventGroup = value;
    }

    /**
     * Gets the value of the version property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getVersion() {
        return version;
    }

    /**
     * Sets the value of the version property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setVersion(String value) {
        this.version = value;
    }

    /**
     * Gets the value of the personId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getPersonId() {
        return personId;
    }

    /**
     * Sets the value of the personId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setPersonId(String value) {
        this.personId = value;
    }

    /**
     * Gets the value of the parentId property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getParentId() {
        return parentId;
    }

    /**
     * Sets the value of the parentId property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setParentId(String value) {
        this.parentId = value;
    }

    /**
     * Gets the value of the relationshipToPrimary property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRelationshipToPrimary() {
        return relationshipToPrimary;
    }

    /**
     * Sets the value of the relationshipToPrimary property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRelationshipToPrimary(String value) {
        this.relationshipToPrimary = value;
    }

    /**
     * Gets the value of the adopted property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAdopted() {
        return adopted;
    }

    /**
     * Sets the value of the adopted property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAdopted(String value) {
        this.adopted = value;
    }

    /**
     * Gets the value of the afn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getAfn() {
        return afn;
    }

    /**
     * Sets the value of the afn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setAfn(String value) {
        this.afn = value;
    }

    /**
     * Gets the value of the ssn property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getSsn() {
        return ssn;
    }

    /**
     * Sets the value of the ssn property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setSsn(String value) {
        this.ssn = value;
    }

    /**
     * Gets the value of the gender property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getGender() {
        return gender;
    }

    /**
     * Sets the value of the gender property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setGender(String value) {
        this.gender = value;
    }

    /**
     * Gets the value of the living property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getLiving() {
        return living;
    }

    /**
     * Sets the value of the living property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setLiving(String value) {
        this.living = value;
    }

}
