//
// This file was generated by the JavaTM Architecture for XML Binding(JAXB) Reference Implementation, vJAXB 2.1.10 in JDK 6 
// See <a href="http://java.sun.com/xml/jaxb">http://java.sun.com/xml/jaxb</a> 
// Any modifications to this file will be lost upon recompilation of the source schema. 
// Generated on: 2011.12.21 at 05:46:39 PM MST 
//


package home.genealogy.schema.all;

import java.util.ArrayList;
import java.util.List;
import javax.xml.bind.annotation.XmlAccessType;
import javax.xml.bind.annotation.XmlAccessorType;
import javax.xml.bind.annotation.XmlAttribute;
import javax.xml.bind.annotation.XmlElement;
import javax.xml.bind.annotation.XmlRootElement;
import javax.xml.bind.annotation.XmlSchemaType;
import javax.xml.bind.annotation.XmlType;


/**
 * <p>Java class for anonymous complex type.
 * 
 * <p>The following schema fragment specifies the expected content contained within this class.
 * 
 * <pre>
 * &lt;complexType>
 *   &lt;complexContent>
 *     &lt;restriction base="{http://www.w3.org/2001/XMLSchema}anyType">
 *       &lt;sequence>
 *         &lt;element ref="{}personName"/>
 *         &lt;element ref="{}nickName" maxOccurs="unbounded" minOccurs="0"/>
 *         &lt;element ref="{}moniker" maxOccurs="unbounded" minOccurs="0"/>
 *       &lt;/sequence>
 *       &lt;attribute name="royalEnumeration" type="{http://www.w3.org/2001/XMLSchema}anySimpleType" />
 *     &lt;/restriction>
 *   &lt;/complexContent>
 * &lt;/complexType>
 * </pre>
 * 
 * 
 */
@XmlAccessorType(XmlAccessType.FIELD)
@XmlType(name = "", propOrder = {
    "personName",
    "nickName",
    "moniker"
})
@XmlRootElement(name = "personIdentification")
public class PersonIdentification {

    @XmlElement(required = true)
    protected PersonName personName;
    protected List<NickName> nickName;
    protected List<String> moniker;
    @XmlAttribute
    @XmlSchemaType(name = "anySimpleType")
    protected String royalEnumeration;

    /**
     * Gets the value of the personName property.
     * 
     * @return
     *     possible object is
     *     {@link PersonName }
     *     
     */
    public PersonName getPersonName() {
        return personName;
    }

    /**
     * Sets the value of the personName property.
     * 
     * @param value
     *     allowed object is
     *     {@link PersonName }
     *     
     */
    public void setPersonName(PersonName value) {
        this.personName = value;
    }

    /**
     * Gets the value of the nickName property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the nickName property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getNickName().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link NickName }
     * 
     * 
     */
    public List<NickName> getNickName() {
        if (nickName == null) {
            nickName = new ArrayList<NickName>();
        }
        return this.nickName;
    }

    /**
     * Gets the value of the moniker property.
     * 
     * <p>
     * This accessor method returns a reference to the live list,
     * not a snapshot. Therefore any modification you make to the
     * returned list will be present inside the JAXB object.
     * This is why there is not a <CODE>set</CODE> method for the moniker property.
     * 
     * <p>
     * For example, to add a new item, do as follows:
     * <pre>
     *    getMoniker().add(newItem);
     * </pre>
     * 
     * 
     * <p>
     * Objects of the following type(s) are allowed in the list
     * {@link String }
     * 
     * 
     */
    public List<String> getMoniker() {
        if (moniker == null) {
            moniker = new ArrayList<String>();
        }
        return this.moniker;
    }

    /**
     * Gets the value of the royalEnumeration property.
     * 
     * @return
     *     possible object is
     *     {@link String }
     *     
     */
    public String getRoyalEnumeration() {
        return royalEnumeration;
    }

    /**
     * Sets the value of the royalEnumeration property.
     * 
     * @param value
     *     allowed object is
     *     {@link String }
     *     
     */
    public void setRoyalEnumeration(String value) {
        this.royalEnumeration = value;
    }

}
